import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./sidenav";

export const metadata: Metadata = {
  title: "pottery gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/pottery.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
